### ISSUE TITLE
Set restart policy for containers

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-platform-reference-implementation#10]
So apparently there is an autostart feature in Docker with the `--restart` option in `docker run` see [here](https://docs.docker.com/reference/run/#restart-policies-restart) for `docker run`and [here](https://docs.docker.com/compose/yml/#working-dir-entrypoint-user-hostname-domainname-mac-address-mem-limit-memswap-limit-privileged-restart-stdin-open-tty-cpu-shares-cpuset-read-only-volume-driver) for `docker-compose`. Default of this is `no` so I would propose to set this to `restart: always` in the docker-compose file.

Also for some reasons I don't have to understand it's currently not possible to change this once the container exists, see [Stackoverflow](https://stackoverflow.com/questions/29603504/how-to-restart-an-existing-docker-container-in-restart-always-mode) for details.

**Comment by retog** [comment]
I created a branch issue-10, having some issues with pundittransformer preventingit to start. It seems this image is still downloading docker-compose, docker-in-docker shold howver no longer be possible as it is not started as privileged. @danilogiacomi, could you look into it? I don't even know where the source of this image is.

**Comment by retog** [comment]
@ktk haven't been hearing from you, did you check out the branch? what's the reason for this issue? If it's about restarting all the containers on system reboot, why not use "unless-stopped"?

This comment: http://serverfault.com/questions/633067/how-do-i-auto-start-docker-containers-at-system-boot#comment833412_649835 suggests tat even with "always" it doesn't restarts when stopped, confused...

**Comment by ktk** [comment]
Unless-stopped is new, that didn't exist when I created the issue. Yes that would make sense now. I didn't try it yet, if it's implemented one can also close this issue.
