### ISSUE TITLE
wen is docker-compose --x-networking needed?

### ISSUE THREAD

**Issue by retog** [fusepoolP3/p3-platform-reference-implementation#16]

**Comment by retog** [comment]
@ktk I can't see why this should be needed as wel link container with `links`. Could you provide more information?

**Comment by ktk** [comment]
Since Docker 1.9.x starting a docker-compose without this option results in the following problem within docker containers:

```
varnish     | DNS lookup(hitch): Name or service not known
```

So in this case varnish does not see hitch anymore which is linked like this:

```
hitch:
 [...]
  links:
   - varnish
```

If I run it with this option it works, but I get this message on startup:

```
Some services ("varnish", "hitch") define links, which are not compatible with Docker networking and will be ignored.
Future versions of Docker will not support links - you should remove them for forwards-compatibility.
```

**Comment by ktk** [comment]
I did not understand yet how to do that properly, need to read into the docker networking stuff again.

**Comment by retog** [comment]
A bit strange, in https://docs.docker.com/compose/compose-file/ doesn't mention anything suggesting that `links` is deprecated.

In your code snipped varnish is linked from hitch, meaning that in the hitch container the name `varnish` resolves. It seems that you are expecting the other direction.

**Comment by ktk** [comment]
Yeah I'm also confused, especially as there is no comparable error message with p3 (with same versions of docker & docker-compose). I will see if changing the order in my setup solves the issue. I also couldn't find much hints in the documentation.

**Comment by retog** [comment]
So closing for now as the platform seems to run as documented in the README. Please add new information and reopen when needed.
