### ISSUE TITLE
Create Docker image for P3-Proxy

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-platform-reference-implementation#2]
See https://github.com/fusepoolP3/p3-proxy

**Comment by retog** [comment]
I don't think it makes sense to create docker images for individual java projects that do not require any non-java dependency to have a docker for them. It can very easily be done though thanks to the spotify maven docker plugin. So if you really think you want a docker imape for the p3-proxy open an issue in  the p3-proxy project and provide and explain the usecase.

**Comment by ktk** [comment]
URL or it didn't happen. What the heck is "the spotify maven docker plugin"?

**Comment by retog** [comment]
URL for what?

To read about the spotify maven docker plugin: https://github.com/spotify/docker-maven-plugin
