### ISSUE TITLE
Investigate how Docker can be/should be used

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-platform-reference-implementation#3]
There are probably multiple approaches:
- Provide a thin container which downloads the necessary binaries from Github
- Provide a fat container which contains all the necessary binaries

Evaluate what is state-of-the-art and how either one of them gets updated in the future.

**Comment by retog** [comment]
The docker image should contain all binaries, getting them at runtime would make little sense.

**Comment by ktk** [comment]
And reopen because your docker script downloads them from the Github repo. You can do comments but don't close these tickets, they are here for a reason.

**Comment by retog** [comment]
I guess you are refrerring to the dockerfile in p3-ldp-marmotta. This is NOT creating a thin container that downloads binaries from Github, it creates an image that contains all necessary binaries. I don't know of any example of a "thin container" and I don't see any reason why we should investigate such a path noone else seems to go along for P3.

**Comment by mainini** [comment]
Can be closed, apparently this workflow should not be used in this case...
